<select name="moedaX" style='margin:0px;width:255px'>
<option value="1">AFEGANE AFEGANIST</option>
<option value="2331">ARIARY MADAGASCAR</option>
<option value="4">AUSTRAL</option>
<option value="6">BALBOA/PANAMA</option>
<option value="5">BATH/TAILANDIA</option>
<option value="2">BIRR</option>
<option value="3">BIRR/ETIOPIA</option>
<option value="8">BOLIVAR VEN</option>
<option value="7">BOLIVAR/VENZUELA</option>
<option value="9">BOLIVIANO/BOLIVIA</option>
<option value="234">BUA</option>
<option value="10">CEDI GANA</option>
<option value="11">COLON/COSTA RICA</option>
<option value="12">COLON/EL SALVADOR</option>
<option value="14">CORDOBA OURO</option>
<option value="13">CORDOBA/NICARAGUA</option>
<option value="15">COROA DINAMARQUESA</option>
<option value="17">COROA ESLOVACA</option>
<option value="16">COROA ESTONIA</option>
<option value="18">COROA ISLND/ISLAN</option>
<option value="19">COROA NORUEGUESA</option>
<option value="20">COROA SUECA</option>
<option value="21">COROA TCHECA</option>
<option value="23">CRUZADO</option>
<option value="22">CRUZADO NOVO</option>
<option value="24">CRUZEIRO</option>
<option value="25">CRUZEIRO</option>
<option value="26">CRUZEIRO REAL</option>
<option value="27">CUPON GEORGIANO</option>
<option value="28">DALASI/GAMBIA</option>
<option value="29">DINAR ARGELINO</option>
<option value="32">DINAR IEMENITA</option>
<option value="34">DINAR IUGOSLAVO</option>
<option value="38">DINAR SERVIO SERVIA</option>
<option value="31">DINAR/BAHREIN</option>
<option value="33">DINAR/IRAQUE</option>
<option value="35">DINAR/JORDANIA</option>
<option value="30">DINAR/KWAIT</option>
<option value="36">DINAR/LIBIA</option>
<option value="37">DINAR/MACEDONIA</option>
<option value="40">DINAR/TUNISIA</option>
<option value="41">DIREITO ESPECIAL</option>
<option value="43">DIRHAM/EMIR.ARABE</option>
<option value="42">DIRHAM/MARROCOS</option>
<option value="44">DOBRA S TOME PRIN</option>
<option value="45">DOLAR AUSTRALIANO</option>
<option value="53">DOLAR BRUNEI</option>
<option value="48">DOLAR CANADENSE</option>
<option value="59">DOLAR CARIBE ORIENTAL</option>
<option value="54">DOLAR CAYMAN</option>
<option value="55">DOLAR CINGAPURA</option>
<option value="49">DOLAR DA GUIANA</option>
<option value="50">DOLAR DA NAMIBIA</option>
<option value="61">DOLAR DOS EUA</option>
<option value="56">DOLAR FIJI</option>
<option value="57">DOLAR HONG KONG</option>
<option value="67">DOLAR IL SALOMAO</option>
<option value="64">DOLAR LIBERIA</option>
<option value="65">DOLAR MALAIO</option>
<option value="236">DOLAR OURO</option>
<option value="60">DOLAR ZIMBABUE</option>
<option value="224">DOLAR-BULGARIA</option>
<option value="223">DOLAR-EX-ALEM.ORI</option>
<option value="225">DOLAR-GRECIA</option>
<option value="226">DOLAR-HUNGRIA</option>
<option value="227">DOLAR-ISRAEL</option>
<option value="228">DOLAR-IUGOSLAVIA</option>
<option value="229">DOLAR-POLONIA</option>
<option value="231">DOLAR-ROMENIA</option>
<option value="46">DOLAR/BAHAMAS</option>
<option value="51">DOLAR/BARBADOS</option>
<option value="52">DOLAR/BELIZE</option>
<option value="47">DOLAR/BERMUDAS</option>
<option value="62">DOLAR/ETIOPIA</option>
<option value="63">DOLAR/JAMAICA</option>
<option value="66">DOLAR/NOVA ZELAND</option>
<option value="68">DOLAR/SURINAME</option>
<option value="78">DOLAR/SURINAME</option>
<option value="58">DOLAR/TRIN. TOBAG</option>
<option value="69">DONGUE/VIETNAN</option>
<option value="70">DRACMA/GRECIA</option>
<option value="71">DRAM ARMENIA REP</option>
<option value="72">ESCUDO CABO VERDE</option>
<option value="73">ESCUDO PORTUGUES</option>
<option value="74">ESCUDO TIMOR LESTE</option>
<option value="222">EURO</option>
<option value="79">FLORIM HOLANDES</option>
<option value="76">FLORIM/ARUBA</option>
<option value="77">FLORIM/SURINAME</option>
<option value="80">FORINT/HUNGRIA</option>
<option value="82">FRANCO BELGA FINA</option>
<option value="81">FRANCO BELGA/BELG</option>
<option value="87">FRANCO CFA BCEAO</option>
<option value="86">FRANCO CFA BEAC</option>
<option value="88">FRANCO CFP</option>
<option value="83">FRANCO CONGOLES</option>
<option value="91">FRANCO FRANCES</option>
<option value="93">FRANCO LUXEMBURGO</option>
<option value="94">FRANCO MALGAXE MADAGA</option>
<option value="95">FRANCO MALI</option>
<option value="97">FRANCO SUICO</option>
<option value="84">FRANCO/BURUNDI</option>
<option value="89">FRANCO/BURUNDI</option>
<option value="85">FRANCO/COMORES</option>
<option value="90">FRANCO/DJIBUTI</option>
<option value="92">FRANCO/GUINE</option>
<option value="96">FRANCO/RUANDA</option>
<option value="235">FUA</option>
<option value="98">GOURDE/HAITI</option>
<option value="99">GUARANI/PARAGUAI</option>
<option value="75">GUILDER ANTILHAS HOLANDESAS</option>
<option value="100">HRYVNIA UCRANIA</option>
<option value="101">IENE</option>
<option value="102">INTI PERUANO</option>
<option value="172">KARBOVANETS</option>
<option value="173">KINA/PAPUA N GUIN</option>
<option value="174">KUNA/CROACIA</option>
<option value="139">KWANZA/ANGOLA</option>
<option value="103">LARI GEORGIA</option>
<option value="104">LAT LETONIA REP</option>
<option value="105">LEK ALBANIA REP</option>
<option value="106">LEMPIRA/HONDURAS</option>
<option value="107">LEONE/SERRA LEOA</option>
<option value="108">LEU/MOLDAVIA, REP</option>
<option value="109">LEU/ROMENIA</option>
<option value="111">LEV/BULGARIA, REP</option>
<option value="112">LIBRA CIP/CHIPRE</option>
<option value="115">LIBRA ESTERLINA</option>
<option value="118">LIBRA ISRAELENSE</option>
<option value="123">LIBRA SUDANESA</option>
<option value="2372">LIBRA SUL SUDANESA</option>
<option value="114">LIBRA/EGITO</option>
<option value="116">LIBRA/FALKLAND</option>
<option value="113">LIBRA/GIBRALTAR</option>
<option value="117">LIBRA/IRLANDA</option>
<option value="119">LIBRA/LIBANO</option>
<option value="122">LIBRA/SIRIA, REP</option>
<option value="121">LIBRA/STA HELENA</option>
<option value="124">LILANGENI/SUAZIL</option>
<option value="125">LIRA ITALIANA</option>
<option value="142">LIRA TURCA</option>
<option value="126">LIRA TURQUIA</option>
<option value="120">LIRA/MALTA</option>
<option value="127">LITA/LITUANIA</option>
<option value="128">LOTI/LESOTO</option>
<option value="130">MANAT ARZEBAIJAO</option>
<option value="129">MARCO</option>
<option value="132">MARCO ALEMAO</option>
<option value="133">MARCO CONV BOSNIA</option>
<option value="134">MARCO FINLANDES</option>
<option value="135">METICAL MOCAMBIQ</option>
<option value="138">NAIRA/NIGERIA</option>
<option value="137">NAKFA ERITREIA</option>
<option value="149">NGULTRUM/BUTAO</option>
<option value="39">NOVA LIBRA SUDANESA</option>
<option value="136">NOVA METICAL/MOCA</option>
<option value="140">NOVO DINAR IUGOSLAVO</option>
<option value="141">NOVO DOLAR/TAIWAN</option>
<option value="110">NOVO LEU/ROMENIA</option>
<option value="131">NOVO MANAT TURCOM</option>
<option value="145">NOVO PESO URUGUAI</option>
<option value="146">NOVO PESO URUGUAI</option>
<option value="143">NOVO PESO/MEXICO</option>
<option value="144">NOVO PESO/MEXICO</option>
<option value="147">NOVO SOL/PERU</option>
<option value="219">NOVO ZAIRE  ZAIRE</option>
<option value="148">NOVO ZAIRE/ZAIRE</option>
<option value="220">NOVO ZAIRE/ZAIRE</option>
<option value="151">PAANGA/TONGA</option>
<option value="232">PALADIO</option>
<option value="152">PATACA/MACAU</option>
<option value="154">PESETA ESPANHOLA</option>
<option value="153">PESETA/ANDORA</option>
<option value="155">PESO ARGENTINO</option>
<option value="156">PESO ARGENTINO</option>
<option value="157">PESO BOLIVIANO</option>
<option value="158">PESO CHILE</option>
<option value="164">PESO MEXICANO</option>
<option value="159">PESO/COLOMBIA</option>
<option value="160">PESO/CUBA</option>
<option value="162">PESO/FILIPINAS</option>
<option value="163">PESO/GUINE BISSAU</option>
<option value="165">PESO/MEXICO</option>
<option value="161">PESO/REP. DOMINIC</option>
<option value="166">PESO/URUGUAIO</option>
<option value="233">PLATINA</option>
<option value="230">PRATA-DEAFI</option>
<option value="167">PULA/BOTSWANA</option>
<option value="169">QUACHA ZAMBIA</option>
<option value="2352">QUACHA ZAMBIA</option>
<option value="168">QUACHA/MALAVI</option>
<option value="170">QUETZAL/GUATEMALA</option>
<option value="171">QUIATE/BIRMANIA</option>
<option value="175">QUIPE/LAOS, REP</option>
<option value="176">RANDE/AFRICA SUL</option>
<option value="177" selected="selected">REAL BRASIL</option>
<option value="178">RENMIMBI IUAN</option>
<option value="2332">RENMINBI HONG KONG</option>
<option value="183">RIAL/ARAB SAUDITA</option>
<option value="179">RIAL/CATAR</option>
<option value="181">RIAL/IEMEN</option>
<option value="182">RIAL/IRAN, REP</option>
<option value="180">RIAL/OMA</option>
<option value="184">RIEL/CAMBOJA</option>
<option value="185">RINGGIT/MALASIA</option>
<option value="186">RUBLO BELARUS</option>
<option value="187">RUBLO/RUSSIA</option>
<option value="195">RUFIA/MALDIVAS</option>
<option value="193">RUPIA/INDIA</option>
<option value="194">RUPIA/INDONESIA</option>
<option value="189">RUPIA/MAURICIO</option>
<option value="190">RUPIA/NEPAL</option>
<option value="196">RUPIA/PAQUISTAO</option>
<option value="191">RUPIA/SEYCHELES</option>
<option value="192">RUPIA/SRI LANKA</option>
<option value="197">SHEKEL/ISRAEL</option>
<option value="198">SOL PERUANO</option>
<option value="199">SOM QUIRGUISTAO</option>
<option value="200">SOM UZBEQUISTAO</option>
<option value="188">SOMONI TADJIQUISTAO</option>
<option value="201">SUCRE EQUADOR</option>
<option value="202">TACA/BANGLADESH</option>
<option value="203">TALA</option>
<option value="204">TALA SAMOA OC</option>
<option value="205">TENGE CAZAQUISTAO</option>
<option value="206">TOLAR/ESLOVENIA</option>
<option value="207">TUGRIK/MONGOLIA</option>
<option value="150">UGUIA MAURITANIA</option>
<option value="208">UNID FOMENTO CHIL</option>
<option value="209">UNID.MONET.EUROP.</option>
<option value="2392">UNIDADE DE FOMENTO DO CHILE</option>
<option value="210">VATU VANUATU</option>
<option value="212">WON COREIA SUL</option>
<option value="211">WON/COREIA NORTE</option>
<option value="213">XELIM AUSTRIACO</option>
<option value="214">XELIM DA TANZANIA</option>
<option value="216">XELIM/QUENIA</option>
<option value="218">XELIM/SOMALIA</option>
<option value="215">XELIM/TANZANIA</option>
<option value="217">XELIM/UGANDA</option>
<option value="221">ZLOTY/POLONIA</option></select>